### ISSUE TITLE
AdaptiveViewGrid - Request: Set static height on Items

### ISSUE THREAD

**Issue by LostLogic** [LanceMcCarthy/UwpProjects#1]
Hi!
Love the AdaptiveViewGrid! It would be helpful if one could set the height of Grid Items to a static property to allow for just filling out the width of a grid dynamically

**Comment by LanceMcCarthy** [comment]
I've chosen not to restrict height for the AdaptiveGridView, you can however find a GridView that does this in the AppStudio source code here: https://github.com/wasteam/waslibs/tree/master/src/AppStudio.Uwp/Controls/ResponsiveGridView
